# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d1489205ed6f83baeb996f70689ed5c543a298ef2e1a811419246dc6861a4b45022100b666aef07b4f26dcb4627d1a7acba871908aa29d1a0dfea833833b603

test:
  secret_key_base: 5832b0236ef6875189531dbf9f38da7809d236103a836902b5a7936d59049841a00332799b8fea6e00a72ab74d9a426e6ba7932841638d05826a6cf08ef39c84

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
